import { useEffect, useState } from "react";
import {
    FaRobot,
    FaArrowRight,
    FaClock,
    FaRoute,
    FaMotorcycle,
    FaTimes,
} from "react-icons/fa";

import API_URL from "../../services/api"; 
const API = `${API_URL}/ai/recommendations`;

export default function AIRecommendation() {
    const [recommendations, setRecommendations] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    // Stores the recommendation whose details are open
    const [selectedRecommendation, setSelectedRecommendation] = useState(null);
    useEffect(() => { fetchRecommendations();}, []);

    async function fetchRecommendations() {
        try {
            setLoading(true);
            setError("");
            const token = localStorage.getItem("token");
            if (!token) { throw new Error("Authentication token not found");}

            const response = await fetch(API, {
                method: "GET",
                headers: {
                    Authorization: `Bearer ${token}`,
                    "Content-Type": "application/json",
                },
            });

            const data = await response.json();

            console.log("AI Recommendations:", data);

            if (!response.ok || !data.success) {
                throw new Error(
                    data.message ||
                        "Failed to load AI recommendations"
                );
            }

            setRecommendations(
                Array.isArray(data.recommendations)
                    ? data.recommendations
                    : []
            );
        } catch (error) {
            console.error(
                "AI Recommendation Error:",
                error
            );

            setError(error.message);
            setRecommendations([]);
        } finally {
            setLoading(false);
        }
    }

    function handleViewDetails(item) {
        setSelectedRecommendation(item);
    }

    function closeDetails() {
        setSelectedRecommendation(null);
    }

    return (
        <div className="bg-white rounded-2xl shadow p-6 w-full">

            {/* ================= HEADER ================= */}

            <div className="flex items-start gap-4">

                <div className="bg-blue-100 text-blue-600 p-3 rounded-xl shrink-0">
                    <FaRobot size={22} />
                </div>

                <div>
                    <h2 className="text-2xl font-bold text-slate-800">
                        AI Recommendations
                    </h2>

                    <p className="text-slate-500 text-sm mt-1">
                        Smart suggestions generated by the
                        dispatch engine.
                    </p>
                </div>

            </div>


            {/* ================= LOADING ================= */}

            {loading && (
                <div className="mt-6 border rounded-xl p-6 text-center">

                    <FaRobot
                        className="mx-auto text-blue-500 animate-pulse"
                        size={30}
                    />

                    <p className="text-slate-500 mt-3">
                        AI is analyzing your orders...
                    </p>

                </div>
            )}


            {/* ================= ERROR ================= */}

            {!loading && error && (
                <div className="mt-6 border border-red-200 bg-red-50 rounded-xl p-5">

                    <p className="text-red-600 font-medium">
                        Failed to load AI recommendations.
                    </p>

                    <p className="text-red-500 text-sm mt-1">
                        {error}
                    </p>

                    <button
                        type="button"
                        onClick={fetchRecommendations}
                        className="mt-3 text-blue-600 font-medium hover:underline"
                    >
                        Try Again
                    </button>

                </div>
            )}


            {/* ================= NO DATA ================= */}

            {!loading &&
                !error &&
                recommendations.length === 0 && (
                    <div className="mt-6 border rounded-xl p-6 text-center">

                        <FaRobot
                            className="mx-auto text-slate-400"
                            size={30}
                        />

                        <p className="text-slate-500 mt-3">
                            No recommendations available
                            right now.
                        </p>

                    </div>
                )}


            {/* ================= LIVE RECOMMENDATIONS ================= */}

            {!loading &&
                !error &&
                recommendations.length > 0 && (

                    <div className="space-y-4 mt-6">

                        {recommendations.map(
                            (item, index) => {

                                const title =
                                    item.title?.toLowerCase() ||
                                    "";

                                let Icon = FaRobot;

                                if (
                                    title.includes("time") ||
                                    title.includes("eta")
                                ) {
                                    Icon = FaClock;
                                } else if (
                                    title.includes("route") ||
                                    title.includes("distance")
                                ) {
                                    Icon = FaRoute;
                                } else if (
                                    title.includes("rider")
                                ) {
                                    Icon = FaMotorcycle;
                                }

                                return (
                                    <div
                                        key={
                                            item._id ||
                                            item.id ||
                                            `recommendation-${index}`
                                        }
                                        className="border rounded-xl p-4 hover:bg-slate-50 transition"
                                    >

                                        <div className="flex gap-3">

                                            {/* Icon */}

                                            <div className="bg-slate-100 p-3 rounded-lg h-fit">
                                                <Icon
                                                    className="text-blue-600"
                                                    size={18}
                                                />
                                            </div>


                                            {/* Content */}

                                            <div className="flex-1 min-w-0">

                                                <h3 className="font-semibold text-slate-800">
                                                    {item.title}
                                                </h3>

                                                <p className="text-slate-500 mt-2 text-sm leading-5">
                                                    {item.description}
                                                </p>


                                                {/* View Details */}

                                                <button
                                                    type="button"
                                                    onClick={() =>
                                                        handleViewDetails(
                                                            item
                                                        )
                                                    }
                                                    className="mt-3 flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium text-sm"
                                                >
                                                    View Details

                                                    <FaArrowRight
                                                        size={12}
                                                    />
                                                </button>

                                            </div>

                                        </div>

                                    </div>
                                );
                            }
                        )}

                    </div>
                )}


            {/* ================= DETAILS PANEL ================= */}

            {selectedRecommendation && (
                <div className="mt-6 border border-blue-200 bg-blue-50 rounded-xl p-5">

                    <div className="flex items-start justify-between gap-4">

                        <div className="flex items-center gap-3">

                            <div className="bg-blue-600 text-white p-3 rounded-lg">
                                <FaRobot size={18} />
                            </div>

                            <div>
                                <h3 className="font-bold text-lg text-slate-800">
                                    {selectedRecommendation.title}
                                </h3>

                                <p className="text-xs text-blue-600 mt-1">
                                    AI Dispatch Insight
                                </p>
                            </div>

                        </div>


                        {/* Close button */}

                        <button
                            type="button"
                            onClick={closeDetails}
                            className="text-slate-500 hover:text-red-500 transition"
                        >
                            <FaTimes />
                        </button>

                    </div>


                    {/* Description */}

                    <div className="mt-5">

                        <p className="text-sm font-semibold text-slate-700">
                            Recommendation
                        </p>

                        <p className="text-slate-600 mt-2 leading-6">
                            {selectedRecommendation.description}
                        </p>

                    </div>


                    {/* Action */}

                    <div className="mt-5">

                        <button
                            type="button"
                            onClick={closeDetails}
                            className="bg-blue-600 text-white px-5 py-2 rounded-lg hover:bg-blue-700 transition"
                        >
                            Got it
                        </button>

                    </div>

                </div>
            )}

        </div>
    );
}