import { FaRobot, FaArrowRight } from "react-icons/fa";

const recommendations = [
  {
    title: "Batch Nearby Orders",
    description:
      "Combine Order #1024 and #1025 to reduce travel distance by 2.8 km.",
  },
  {
    title: "Assign Faster Rider",
    description:
      "Rider R-18 can complete the delivery 9 minutes earlier.",
  },
  {
    title: "Traffic Alert",
    description:
      "Heavy traffic detected on Route A. Switch to Route B to save time.",
  },
];

export default function AIRecommendation() {
  return (
    <div className="bg-white rounded-2xl shadow p-6">
      <div className="flex items-center gap-3 mb-6">
        <FaRobot className="text-blue-600 text-3xl" />

        <div>
          <h2 className="text-2xl font-bold">
            AI Recommendations
          </h2>

          <p className="text-slate-500 text-sm">
            Smart suggestions generated by the dispatch engine.
          </p>
        </div>
      </div>

      <div className="space-y-4">
        {recommendations.map((item, index) => (
          <div
            key={index}
            className="border rounded-xl p-4 hover:bg-slate-50 transition"
          >
            <h3 className="font-semibold text-slate-800">
              {item.title}
            </h3>

            <p className="text-slate-500 mt-2 text-sm">
              {item.description}
            </p>

            <button className="mt-3 flex items-center gap-2 text-blue-600 hover:text-blue-700 font-medium">
              View Details
              <FaArrowRight size={12} />
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}